# Generated by Django 2.2.7 on 2019-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idArticulo', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListasCompras',
            fields=[
                ('idListaCompra', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('idCliente', models.IntegerField()),
                ('idArticulo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
