# Generated by Django 2.2.7 on 2019-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionListaCompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listascompras',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
